name: Validate PR
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build_project:
    if: startsWith(github.head_ref, 'renovate')
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: |
          ./gradlew :dependency:build --no-daemon

      - name: Auto merge
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })