# This is the storage type the plugin will use
# Choose one of the options below
# h2, sqlite, mysql, mariadb
storage-type: h2

# Amount of decimal places allowed within balances
# -1 to disable rounding
decimal-places: 3

# Whether you want players to be able to withdraw
# they're money to 'checks' or 'banknotes'
banknotes: false

# Whether you want these commands enabled
commands:
  balance: true
  balancetop: true
  economy: true
  pay: true
  request: false
  custombalance: false
  customeconomy: false

# Whether you want custom currency functionality enabled.
custom-currencies: false

# Number in hours (decimals allowed)
# 0 to disable
backup-interval: 1

# Number in seconds
# 0 to disable
balancetop-interval: 5
autosave-accounts-interval: 60

database-information:
  database: database-name
  address: localhost
  port: 0
  username: username
  password: password
# This is used for datasource properties (Only use if knowledgeable)
#  advanced-settings:
#    property: value