# This is the storage type the plugin will use
# Choose one of the options below
# h2 - faster than sqlite (still working out possible bugs, it does function though)
# sqlite - is faster and more efficient
# mysql - if you're using this, you know what it does...
# json - allows for editing accounts via files
storage-type: sqlite

# Amount of decimal places allowed within balances
# -1 to disable rounding
decimal-places: 3

# Whether you want players to be able to withdraw
# they're money to 'checks' or 'banknotes'
banknotes: false

# Whether you want these commands enabled
commands:
  balance: true
  balancetop: true
  economy: true
  pay: true

# Whether you want custom currency functionality enabled.
custom-currencies: false

# Whether you want these commands enabled
custom-currency-commands:
  custombalance: true
  customeconomy: true

# Number in hours (decimals allowed)
# 0 to disable
backup-interval: 1

# Number in seconds
# 0 to disable
balancetop-interval: 5

MySQL:
  name: qualityeconomy
  # host:port
  host: localhost:3306
  user: root
  password: root
