# This is the storage type the plugin will use
# Choose one of the options below
# h2
# sqlite
# mysql
# json
storage-type: sqlite

# Amount of decimal places allowed within balances
# -1 to disable rounding
decimal-places: 3

# Whether you want players to be able to withdraw
# they're money to 'checks' or 'banknotes'
banknotes: false

# Whether you want these commands enabled
# WARNING - Changing pay & request from true to false irreversibly erases the toggle settings
commands:
  balance: true
  balancetop: true
  economy: true
  pay: true
  request: false
  custombalance: false
  customeconomy: false

# Whether you want custom currency functionality enabled.
custom-currencies: false

# Number in hours (decimals allowed)
# 0 to disable
backup-interval: 1

# Number in seconds
# 0 to disable
balancetop-interval: 5
autosave-accounts-interval: 60

MySQL:
  name: qualityeconomy
  host: localhost:3306
  user: root
  password: root
