# sqlite, yaml, json
storage-type: sqlite

# Amount of decimal places allowed within balances
decimal-places: 4

banknotes: false

# Whether you want these commands enabled
commands:
  balance: true
  balancetop: true
  economy: true
  pay: true

# Number in hours (decimals allowed)
# 0 to disable
backup-interval: 1

MySQL:
  port: 3306
  user: root
  password: root

# Don't touch this
version: ${project.version}