name: QualityEconomy
author: "ImNotStable"
main: com.imnotstable.qualityeconomy.QualityEconomy
version: '${project.version}'
api-version: 1.18
load: STARTUP
softdepend: [ PlaceholderAPI, Vault ]
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - org.postgresql:postgresql:42.7.2
  - com.h2database:h2:2.2.224
  - org.mongodb:mongodb-driver-sync:5.0.0
  - com.google.code.gson:gson:2.10.1