name: QualityEconomy
author: "ImNotStable"
main: com.imnotstable.qualitygambling.QualityGambling
version: '@version@'
api-version: 1.19
load: STARTUP
dependencies:
  server:
    QualityEconomy:
      load: BEFORE
      required: true
      join-classpath: true