name: Auto Dependabot Merge

on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check dependency
        id: check
        run: |
          DEPENDENCY_NAME=$(echo '${{ steps.metadata.outputs.dependency }}' | jq -r '.name')
          if [[ "$DEPENDENCY_NAME" == "paper-api" ]]; then
            exit 1
          fi
        continue-on-error: true
      - name: Approve and Merge a PR
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          gh pr review --approve "$PR_URL"
          gh pr merge "$PR_URL" --merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GH_PAT}}