# This is the storage type the plugin will use
# Choose one of the options below
# h2, sqlite, mysql, mariadb
storage-type: h2

# Number in seconds
# 0 to disable
backup-interval: 21600
autosave-accounts-interval: 60

database-information:
  database: database-name
  address: localhost
  port: 0
  username: username
  password: password
  advanced-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000

# Notify admins when there is a new version of QualityEconomy
update-notifications: true
