name: QualityEconomy
author: "ImNotStable"
main: com.imnotstable.qualityeconomy.QualityEconomy
loader: com.imnotstable.qualityeconomy.QualityLoader
version: '@version@'
api-version: "1.21.1"
load: STARTUP
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true